# vim:sw=2:et:
# https://help.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow
name: "Test - Erlang 22.3"
on:
  push:
  repository_dispatch:
    types:
      - new-commit-to-dep-release-branch
jobs:
  # vim:sw=2:et:
  checks:
    name: checks
    runs-on: ubuntu-18.04
    steps:
      - name: CHECKOUT REPOSITORY
        uses: actions/checkout@v2
      # https://github.com/marketplace/actions/setup-elixir
      - name: CONFIGURE OTP & ELIXIR
        uses: actions/setup-elixir@v1
        with:
          otp-version: 22.3
          # https://github.com/elixir-lang/elixir/releases
          elixir-version: 1.8.0
      - name: CHECK RABBITMQ COMPONENTS
        # https://github.community/t5/GitHub-Actions/How-can-I-set-an-expression-as-an-environment-variable-at/m-p/41804/highlight/true#M4751
        id: ref
        run: |
          branch_or_tag_name=${GITHUB_REF#refs/*/}
          echo "::set-output name=branch_or_tag_name::$branch_or_tag_name"
          make check-rabbitmq-components.mk base_rmq_ref=master current_rmq_ref=$branch_or_tag_name
      # https://help.github.com/en/actions/configuring-and-managing-workflows/caching-dependencies-to-speed-up-workflows
      - name: CACHE DEPS
        uses: actions/cache@v1
        with:
          path: deps
          key: otp-22.3_git-${{ github.sha }}_deps
      - name: RESOLVE & COMPILE DEPS
        run: |
          make deps test-deps base_rmq_ref=master current_rmq_ref=${{ steps.ref.outputs.branch_or_tag_name }}
          echo "Capture versions of the RabbitMQ components used in this workflow..."
          make rabbit-rabbitmq-deps.mk
          mv rabbit-rabbitmq-deps.mk deps/
          echo "Remove directories not used in the subsequent jobs..."
          rm -fr deps/*/{.git,test}
      - name: UPLOAD DEPS VERSIONS
        uses: actions/upload-artifact@v2-preview
        with:
          name: rabbit-rabbitmq-deps.mk
          path: deps/rabbit-rabbitmq-deps.mk
      - name: CHECK CROSS REFERENCES
        run: |
          make xref base_rmq_ref=master current_rmq_ref=${{ steps.ref.outputs.branch_or_tag_name }}
      - name: COMPILE FOR TEST
        run: |
          make test-build base_rmq_ref=master current_rmq_ref=${{ steps.ref.outputs.branch_or_tag_name }}
      - name: CACHE SECONDARY UMBRELLAS
        if: success() && 'latest' == 'oldest'
        uses: actions/cache@v1
        with:
          path: umbrellas
          key: secondary-umbrellas-v3.7.x-v3.8.3-erlang-22.3-rev1
      - name: PREPARE SECONDARY UMBRELLA COPIES
        if: success() && 'latest' == 'oldest'
        run: |
          set -x
          if ! test -f umbrellas/.ready; then
            git config --global advice.detachedHead false
            # We recreate the directory in case something incomplete was
            # cached.
            rm -rf umbrellas
            mkdir -p umbrellas
            git clone \
              https://github.com/rabbitmq/rabbitmq-public-umbrella.git \
              umbrellas/master
            make -C umbrellas/master co # To get RabbitMQ components.
            for version in v3.7.x v3.8.3; do
              umbrella="umbrellas/$version"
              # We copy the master Umbrella and checkout the appropriate tag.
              cp -a umbrellas/master "$umbrella"
              git -C "$umbrella" checkout "master"
              make -C "$umbrella" up BRANCH="$version"
              # To remove third-party deps which were checked out when the
              # projects were on the `master` branch. Thus, possibly not the
              # version pinning we expect. We update the Umbrella one last time
              # to fetch the correct third-party deps.
              make -C "$umbrella" clean-3rd-party-repos
              make -C "$umbrella" up
              make -C "$umbrella/deps/rabbit" test-dist
              rm -fr "$umbrella"/deps/*/{.git,test} "$umbrella"/.git
            done
            rm -fr umbrellas/master
            touch umbrellas/.ready
          fi
  # vim:sw=2:et:
  dialyzer:
    name: dialyzer
    needs: [checks]
    runs-on: ubuntu-18.04
    steps:
      - name: CHECKOUT REPOSITORY
        if: success() && 'latest' == 'latest'
        uses: actions/checkout@v2
      # https://github.com/marketplace/actions/setup-elixir
      - name: CONFIGURE OTP & ELIXIR
        if: success() && 'latest' == 'latest'
        uses: actions/setup-elixir@v1
        with:
          otp-version: 22.3
          # https://github.com/elixir-lang/elixir/releases
          elixir-version: 1.8.0
      - name: CACHE DEPS
        if: success() && 'latest' == 'latest'
        uses: actions/cache@v1
        with:
          path: deps
          key: otp-22.3_git-${{ github.sha }}_deps
      - name: CACHE DIALYZER PLT
        if: success() && 'latest' == 'latest'
        uses: actions/cache@v1
        with:
          path: .rabbit.plt
          key: plt-rabbit-erlang-22.3-g${{ github.sha }}
      - name: RUN DIALYZER
        if: success() && 'latest' == 'latest'
        run: |
          branch_or_tag_name=${GITHUB_REF#refs/*/}
          make dialyze \
            base_rmq_ref=master \
            current_rmq_ref=$branch_or_tag_name \
            FULL=
  # vim:sw=2:et:
  eunit:
    needs: [checks]
    # https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#contexts
    name: eunit
    runs-on: ubuntu-18.04
    steps:
      - name: CHECKOUT REPOSITORY
        uses: actions/checkout@v2
      # https://github.com/marketplace/actions/setup-elixir
      - name: CONFIGURE OTP & ELIXIR
        uses: actions/setup-elixir@v1
        with:
          otp-version: 22.3
          # https://github.com/elixir-lang/elixir/releases
          elixir-version: 1.8.0
      - name: CACHE DEPS
        uses: actions/cache@v1
        with:
          path: deps
          key: otp-22.3_git-${{ github.sha }}_deps
      - name: RUN TESTS
        run: |
          ! test -d ebin || touch ebin/*
          branch_or_tag_name=${GITHUB_REF#refs/*/}
          make eunit \
            base_rmq_ref=master \
            current_rmq_ref=$branch_or_tag_name \
            FULL= \
            FAIL_FAST=1 \
            SKIP_AS_ERROR=1
  # vim:sw=2:et:
  capture-tested-deps-versions:
    needs:
      - dialyzer
      - eunit
    runs-on: ubuntu-18.04
    steps:
      - name: CHECKOUT REPOSITORY
        uses: actions/checkout@v2
      - name: CACHE DEPS
        uses: actions/cache@v1
        with:
          path: deps
          key: otp-22.3_git-${{ github.sha }}_deps
      - name: FORMAT GIT REF
        # https://github.community/t5/GitHub-Actions/How-can-I-set-an-expression-as-an-environment-variable-at/m-p/41804/highlight/true#M4751
        id: ref
        run: |
          branch_or_tag_name=${GITHUB_REF#refs/*/}
          echo "::set-output name=branch_or_tag_name::$branch_or_tag_name"
      - name: UPLOAD TO S3
        if: github.ref == 'refs/heads/master'
        # https://github.com/marketplace/actions/s3-file-upload
        uses: zdurham/s3-upload-github-action@master
        env:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         AWS_REGION: ${{ secrets.AWS_REGION }}
         FILE: deps/rabbit-rabbitmq-deps.mk
         S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
         S3_KEY: rabbitmq-server/${{ steps.ref.outputs.branch_or_tag_name }}/${{ github.run_id }}/otp-22.3/rabbit-rabbitmq-deps.mk
